#%RAML 1.0 DataType

description: Profile update.
displayName: ProfileUpdate
type: object
properties:
  firstName:
    required: false
    type: string
  lastName:
    required: false
    type: string
  age:
    required: false
    type: integer
    minimum: 1
  gender:
    required: false
    type: string
    enum:
      - M
      - m
      - F
      - f
example: !include ../examples/profileUpdate.json
