#%RAML 1.0 DataType

description: Token message.
displayName: TokenMessage
type: object
properties:
  message:
    required: true
    type: string
  token
    required: true
    type: string
example: !include ../examples/tokenMessage.json
