#%RAML 1.0 DataType

description: User schema.
displayName: User
type: object
properties:
  username:
    required: true
    type: string
    minLength: 5
  password:
    required: true
    type: string
    minLength: 5
  admin:
    required: true
    type: boolean
example: !include ../examples/user.json
