#%RAML 1.0 ResourceType

usage: To be applied to any collection-based resource.
type: base
get?:
  description: Get all <<resourcePathName>>the in the collection.
post?:
  description: Create a new <<resourcePathName | !singularize>>.
