#%RAML 1.0 Library

usage: Provides access to defined data types.
types:
  FilteredAndPagedProfileSearchResults: !include ../dataTypes/filteredAndPagedProfileSearchResults.raml
  FilteredAndPagedUserSearchResults: !include ../dataTypes/filteredAndPagedUserSearchResults.raml
  FilteredProfileSearchResults: !include ../dataTypes/filteredProfileSearchResults.raml
  FilteredUserSearchResults: !include ../dataTypes/filteredUserSearchResults.raml
  Message: !include ../dataTypes/message.raml
  Profile: !include ../dataTypes/profile.raml
  ProfileUpdate: !include ../dataTypes/profileUpdate.raml
  TokenMessage: !include ../dataTypes/tokenMessage.raml
  User: !include ../dataTypes/user.raml
  UserInfo: !include ../dataTypes/userInfo.raml
  UserUpdate: !include ../dataTypes/userUpdate.raml
