#%RAML 1.0 Library

usage: Provides access to defined traits.
traits:
  filterable: !include ../traits/filterable.raml
  jwtSecured: !include ../traits/jwtSecured.raml
  pageable: !include ../traits/pageable.raml
