#%RAML 1.0

title: Profile
description: Profile API.
version: 1.1.0
#baseUri:
protocols:
  - HTTP
mediaType: application/json
securedBy:
  - securitySchemes_.jwt
uses:
  dataTypes_: ./libs/dataTypes.raml
  resourceTypes_: ./libs/resourceTypes.raml
  securitySchemes_: ./libs/securitySchemes.raml
  traits_: ./libs/traits.raml
documentation:
  - title: Headline
    content: !include docs/headline.md

/profiles:
  type: resourceTypes_.Collection
  is:
    - traits_.jwtSecured
  get:
    is:
      - traits_.filterable
      - traits_.pageable
    queryParameters:
      firstName:
        description: Query by first name.
        type: string
        required: false
        example: sampleFirstName
      lastName:
        description: Query by last name.
        type: string
        required: false
        example: sampleLastName
      age:
        description: Query by age.
        type: integer
        required: false
        example: 10
      gender:
        description: Query by gender.
        type: string
        required: false
        example: M
      id:
        description: Query by id.
        type: string
        required: false
        example: "77777"
    responses:
      200:
        description: OK.
        body:
          type: dataTypes_.FilteredProfileSearchResults | dataTypes_.FilteredAndPagedProfileSearchResults
          examples:
            FilteredProfileSearchResults: !include ./examples/filteredProfileSearchResults.json
            FilteredAndPagedProfileSearchResults: !include ./examples/filteredAndPagedProfileSearchResults.json
  post:
    body:
      type: dataTypes_.Profile
      example: !include ./examples/profile.json
  /{id}:
    type: resourceTypes_.Item
    is:
      - traits_.jwtSecured
    get:
      responses:
        200:
          description: OK.
          body:
            type: dataTypes_.FilteredProfileSearchResults
            example: !include ./examples/filteredProfileSearchResults.json
    put:
      body:
        type: dataTypes_.ProfileUpdate
        example: !include ./examples/profileUpdate.json
    delete:

/users:
  type: resourceTypes_.Collection
  is:
    - traits_.jwtSecured
  get:
    is:
      - traits_.filterable
      - traits_.pageable
    queryParameters:
      username:
        description: Query by username.
        type: string
        required: false
        example: sampleUserName
      admin:
        description: Query by admin credential.
        type: boolean
        required: false
        example: true
    responses:
      200:
        description: OK.
        body:
          type: dataTypes_.FilteredUserSearchResults | dataTypes_.FilteredAndPagedUserSearchResults
          examples:
            FilteredUserSearchResults: !include ./examples/filteredUserSearchResults.json
            FilteredAndPagedUserSearchResults: !include ./examples/filteredAndPagedUserSearchResults.json
  post:
    body:
      type: dataTypes_.User
      example: !include ./examples/user.json
  /{username}:
    type: resourceTypes_.Item
    is:
      - traits_.jwtSecured
    get:
      responses:
        200:
          description: OK.
          body:
            type: dataTypes_.FilteredUserSearchResults
            example: !include ./examples/filteredUserSearchResults.json
    put:
      body:
        type: dataTypes_.UserUpdate
        example: !include ./examples/userUpdate.json
    delete:

/signup:
  post:
    body:
      type: dataTypes_.UserInfo
      example: !include ./examples/userInfo.json
    responses:
      200:
        description: OK.
        body:
            type: dataTypes_.Message
            example: !include ./examples/message.json
      400:
        description: Bad request.
        body:
          application/json:
            type: dataTypes_.Message
            example: !include ./examples/message.json
      500:
        description: Internal server error.
        body:
          application/json:
            type: dataTypes_.Message
            example: !include ./examples/message.json

/login:
  post:
    body:
      type: dataTypes_.UserInfo
      example: !include ./examples/userInfo.json
    responses:
      200:
        description: OK.
        body:
            type: dataTypes_.Message
            example: !include ./examples/message.json
      400:
        description: Bad request.
        body:
          application/json:
            type: dataTypes_.Message
            example: !include ./examples/message.json
      500:
        description: Internal server error.
        body:
          application/json:
            type: dataTypes_.Message
            example: !include ./examples/message.json

/docs:
  get:
    responses:
      200:
        description: OK.
        body:
          text/html:
