#%RAML 1.0

title: Profile API
description: Profile API.
version: 1.1.0
#baseUri:
protocols:
  - HTTP
mediaType: application/json
documentation:
  - title: Headline
    content: !include docs/headline.md

/profiles:
  get:
    queryParameters:
      firstName:
        description: Query by first name.
        type: string
        required: false
        example: sampleFirstName
